package Interface.Corba.DEMS;


/**
* DEMS/ProjectIdentifierHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Project.idl
* Wednesday, October 17, 2018 7:07:31 o'clock PM EDT
*/

abstract public class ProjectIdentifierHelper
{
  private static String  _id = "IDL:DEMS/ProjectIdentifier:1.0";

  public static void insert (org.omg.CORBA.Any a, ProjectIdentifier that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProjectIdentifier extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "m_Prefix",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "m_UUID",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ProjectIdentifierHelper.id (), "ProjectIdentifier", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProjectIdentifier read (org.omg.CORBA.portable.InputStream istream)
  {
    ProjectIdentifier value = new ProjectIdentifier ();
    value.m_Prefix = istream.read_string ();
    value.m_UUID = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProjectIdentifier value)
  {
    ostream.write_string (value.m_Prefix);
    ostream.write_long (value.m_UUID);
  }

}
