package Interface.Corba.DEMS;

/**
* DEMS/ProjectIdentifierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Project.idl
* Wednesday, October 17, 2018 7:07:31 o'clock PM EDT
*/

public final class ProjectIdentifierHolder implements org.omg.CORBA.portable.Streamable
{
  public ProjectIdentifier value = null;

  public ProjectIdentifierHolder ()
  {
  }

  public ProjectIdentifierHolder (ProjectIdentifier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProjectIdentifierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProjectIdentifierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProjectIdentifierHelper.type ();
  }

}
