package Interface.Corba.DEMS;


/**
* DEMS/Project.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Project.idl
* Wednesday, October 17, 2018 7:07:31 o'clock PM EDT
*/

public final class Project implements org.omg.CORBA.portable.IDLEntity
{
  public ProjectIdentifier m_Id = null;
  public String m_Name = null;
  public String m_Client = null;

  public Project ()
  {
  } // ctor

  public Project (ProjectIdentifier _m_Id, String _m_Name, String _m_Client)
  {
    m_Id = _m_Id;
    m_Name = _m_Name;
    m_Client = _m_Client;
  } // ctor

} // class Project
