package Interface.Corba.DEMS;


/**
* DEMS/ProjectIdentifier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Project.idl
* Wednesday, October 17, 2018 7:07:31 o'clock PM EDT
*/

public final class ProjectIdentifier implements org.omg.CORBA.portable.IDLEntity
{
  public String m_Prefix = null;
  public int m_UUID = (int)0;

  public ProjectIdentifier ()
  {
  } // ctor

  public ProjectIdentifier (String _m_Prefix, int _m_UUID)
  {
    m_Prefix = _m_Prefix;
    m_UUID = _m_UUID;
  } // ctor

} // class ProjectIdentifier
