package Interface.Corba.DEMS;


/**
* DEMS/RegionalRecordManipulatorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegionalRecordManipulator.idl
* Thursday, October 25, 2018 9:48:52 o'clock PM EDT
*/

public abstract class RegionalRecordManipulatorPOA extends org.omg.PortableServer.Servant
 implements RegionalRecordManipulatorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createMRecord", new java.lang.Integer (0));
    _methods.put ("createERecord", new java.lang.Integer (1));
    _methods.put ("editRecord", new java.lang.Integer (2));
    _methods.put ("transferRecord", new java.lang.Integer (3));
    _methods.put ("getRecordCount", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DEMS/RegionalRecordManipulator/createMRecord
       {
         try {
           String managerID = in.read_string ();
           String firstName = in.read_string ();
           String lastName = in.read_string ();
           int employeeID = in.read_long ();
           String mailID = in.read_string ();
           Project projects = ProjectHelper.read (in);
           String location = in.read_string ();
           String $result = null;
           $result = this.createMRecord (managerID, firstName, lastName, employeeID, mailID, projects, location);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (RemoteException $ex) {
           out = $rh.createExceptionReply ();
           RemoteExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // DEMS/RegionalRecordManipulator/createERecord
       {
         try {
           String managerID = in.read_string ();
           String firstName = in.read_string ();
           String lastName = in.read_string ();
           int employeeID = in.read_long ();
           String mailID = in.read_string ();
           String projectId = in.read_string ();
           String $result = null;
           $result = this.createERecord (managerID, firstName, lastName, employeeID, mailID, projectId);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (RemoteException $ex) {
           out = $rh.createExceptionReply ();
           RemoteExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // DEMS/RegionalRecordManipulator/editRecord
       {
         try {
           String managerID = in.read_string ();
           String recordID = in.read_string ();
           String feildName = in.read_string ();
           org.omg.CORBA.Any newValue = in.read_any ();
           String $result = null;
           $result = this.editRecord (managerID, recordID, feildName, newValue);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (RemoteException $ex) {
           out = $rh.createExceptionReply ();
           RemoteExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // DEMS/RegionalRecordManipulator/transferRecord
       {
         try {
           String managerID = in.read_string ();
           String recordID = in.read_string ();
           String remoteSeverName = in.read_string ();
           String $result = null;
           $result = this.transferRecord (managerID, recordID, remoteSeverName);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (RemoteException $ex) {
           out = $rh.createExceptionReply ();
           RemoteExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // DEMS/RegionalRecordManipulator/getRecordCount
       {
         try {
           String managerID = in.read_string ();
           String $result = null;
           $result = this.getRecordCount (managerID);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (RemoteException $ex) {
           out = $rh.createExceptionReply ();
           RemoteExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // DEMS/RegionalRecordManipulator/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DEMS/RegionalRecordManipulator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RegionalRecordManipulator _this() 
  {
    return RegionalRecordManipulatorHelper.narrow(
    super._this_object());
  }

  public RegionalRecordManipulator _this(org.omg.CORBA.ORB orb) 
  {
    return RegionalRecordManipulatorHelper.narrow(
    super._this_object(orb));
  }


} // class RegionalRecordManipulatorPOA
