package Interface.Corba.DEMS;

/**
* DEMS/RegionalRecordManipulatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegionalRecordManipulator.idl
* Wednesday, October 17, 2018 7:04:01 o'clock PM EDT
*/

public final class RegionalRecordManipulatorHolder implements org.omg.CORBA.portable.Streamable
{
  public RegionalRecordManipulator value = null;

  public RegionalRecordManipulatorHolder ()
  {
  }

  public RegionalRecordManipulatorHolder (RegionalRecordManipulator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RegionalRecordManipulatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RegionalRecordManipulatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RegionalRecordManipulatorHelper.type ();
  }

}
