package DEMS;


/**
* DEMS/RegionalRecordManipulatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegionalRecordManipulator.idl
* Thursday, October 25, 2018 9:48:52 o'clock PM EDT
*/

public interface RegionalRecordManipulatorOperations 
{
  String createMRecord (String managerID, String firstName, String lastName, int employeeID, String mailID, DEMS.Project projects, String location) throws DEMS.RemoteException;
  String createERecord (String managerID, String firstName, String lastName, int employeeID, String mailID, String projectId) throws DEMS.RemoteException;
  String editRecord (String managerID, String recordID, String feildName, org.omg.CORBA.Any newValue) throws DEMS.RemoteException;
  String transferRecord (String managerID, String recordID, String remoteSeverName) throws DEMS.RemoteException;
  String getRecordCount (String managerID) throws DEMS.RemoteException;
  void shutdown ();
} // interface RegionalRecordManipulatorOperations
