package Interface.Corba.DEMS;


/**
* DEMS/RemoteException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegionalRecordManipulator.idl
* Wednesday, October 17, 2018 7:04:01 o'clock PM EDT
*/

public final class RemoteException extends org.omg.CORBA.UserException
{
  public String what = null;

  public RemoteException ()
  {
    super(RemoteExceptionHelper.id());
  } // ctor

  public RemoteException (String _what)
  {
    super(RemoteExceptionHelper.id());
    what = _what;
  } // ctor


  public RemoteException (String $reason, String _what)
  {
    super(RemoteExceptionHelper.id() + "  " + $reason);
    what = _what;
  } // ctor

} // class RemoteException
