package Interface.Corba.DEMS;


/**
* DEMS/RegionalRecordManipulatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegionalRecordManipulator.idl
* Wednesday, October 17, 2018 7:04:01 o'clock PM EDT
*/

abstract public class RegionalRecordManipulatorHelper
{
  private static String  _id = "IDL:DEMS/RegionalRecordManipulator:1.0";

  public static void insert (org.omg.CORBA.Any a, RegionalRecordManipulator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RegionalRecordManipulator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RegionalRecordManipulatorHelper.id (), "RegionalRecordManipulator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RegionalRecordManipulator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RegionalRecordManipulatorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RegionalRecordManipulator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RegionalRecordManipulator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RegionalRecordManipulator)
      return (RegionalRecordManipulator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RegionalRecordManipulatorStub stub = new _RegionalRecordManipulatorStub ();
      stub._set_delegate(delegate);
      return (RegionalRecordManipulator) stub;
    }
  }

  public static RegionalRecordManipulator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RegionalRecordManipulator)
      return (RegionalRecordManipulator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RegionalRecordManipulatorStub stub = new _RegionalRecordManipulatorStub ();
      stub._set_delegate(delegate);
      return (RegionalRecordManipulator) stub;
    }
  }

}
