package Interface.Corba.DEMS;


/**
* DEMS/RegionalRecordManipulator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegionalRecordManipulator.idl
* Wednesday, October 17, 2018 7:04:01 o'clock PM EDT
*/

public interface RegionalRecordManipulator extends RegionalRecordManipulatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RegionalRecordManipulator
