package Interface.Corba.DEMS;


/**
* DEMS/RegionalRecordManipulatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegionalRecordManipulator.idl
* Wednesday, October 17, 2018 7:04:01 o'clock PM EDT
*/

public interface RegionalRecordManipulatorOperations 
{
  String createMRecord (String firstName, String lastName, int employeeID, String mailID, Project projects, String location) throws RemoteException;
  String createERecord (String firstName, String lastName, int employeeID, String mailID, String projectId) throws RemoteException;
  String editRecord (String recordID, String feildName, org.omg.CORBA.Any newValue) throws RemoteException;
  String getRecordCount () throws RemoteException;
  void shutdown ();
} // interface RegionalRecordManipulatorOperations
