package Interface.AdditionApp;

/**
* AdditionApp/AdditionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, October 17, 2018 6:01:07 o'clock PM EDT
*/

public final class AdditionHolder implements org.omg.CORBA.portable.Streamable
{
  public Addition value = null;

  public AdditionHolder ()
  {
  }

  public AdditionHolder (Addition initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdditionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdditionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdditionHelper.type ();
  }

}
